version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: unless-stopped
  celery:
    build: .
    restart: always
    command: celery -A mailing worker -l info -P solo
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - db
  dashboard:
    container_name: dashboard
    build: .
    command: celery -A mailing flower --port=5555 broker=redis://redis:6379/0
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - web
      - celery